version: '3.8'

services:
  store-nginx:
    image: nginx:1.19.3-alpine
    container_name: store-nginx
    restart: always
    volumes:
        - ./out:/etc/nginx/html:ro
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - store-service
    ports:
      - "80:80"

  store-service:
    image: boyone/store-service-stub
    ports:
      - '2525:2525'
      - '8000:8000'
    volumes:
      - ./imposters:/imposters
